---
title: "Craywatch dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bg: "#ffffff"
      fg: "#356196" 
      primary: "#c04384"
      navbar-bg: "#000000"
      base_font: 
        google: Prompt
      heading_font:
        google: Sen
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Load libraries:
library(tidyverse)      # to do datascience
library(here)           # to work easily with paths
library(sf)             # to work with geospatial vector data
library(leaflet)        # to make dynamic maps
library(DT)             # to make interactive tables
library(flexdashboard)  # to make dashboards


# Read data
cray_df <- readr::read_tsv(
  here::here("data", "20250224", "20250224_craywatch_cleaned.txt"),
  na = "",
  guess_max = 10000
)
```

Crayfish distribution
=====================================  

### Number of observations

```{r}
n_obs_per_month_species <-
  cray_df %>%
  count(year, month, species) %>%
  # combine year and month to a single date
  mutate(date = as_date(paste0(year, "-", month, "-01"))) %>%
  arrange(date, species) %>%
  relocate(date, species, n, everything())

ggplot(n_obs_per_month_species,
       aes(x = date, y = n, fill = species)) +
  geom_bar(stat = "identity") +
  # Use inferno colors for the species
  scale_fill_viridis_d(option = "inferno") +
  # Add title and labels
  labs(title = "Number of observations per month and species",
       x = "", y = "Number of observations") +
  scale_x_date(breaks = n_obs_per_month_species$date, date_labels = "%b") +
  theme_minimal()
```

### Observations of Crayfish species

```{r}
cray_fl <- sf::st_as_sf(cray_df,
                        coords = c("decimalLongitude", "decimalLatitude"),
                        crs = 4326)

# Create a palette that maps species to colors
pal <- colorFactor("inferno", cray_fl$species)
leaflet(cray_fl) %>%
  addTiles() %>%
  addCircleMarkers(popup = ~paste0(cray_fl$eventDate, ": ", cray_fl$species),
                   color = pal(cray_fl$species),
                   stroke = FALSE,
                   fillOpacity = 0.5,
                   radius = 4) %>%
  addLegend(pal = pal, values = ~species,
            position = "bottomright")
```

Citizen science {data-orientation=rows}
=====================================  

Row
-------------------------------------

### Citizen science data for detecting crayfish

```{r}
dataset_name <- paste("Waarnemingen.be - Non-native animal occurrences in",
  "Flanders and the Brussels Capital Region, Belgium")
n_obs_craywatch <- cray_df %>%
  filter(datasetName == dataset_name) %>%
  nrow()
tot_obs <- nrow(cray_df)
percentage_craywatch <- n_obs_craywatch / tot_obs * 100

gauge(percentage_craywatch, min = 0, max = 100, symbol = "%",
      gaugeSectors(success = c(80, 100), warning = c(40, 79), danger = c(0, 39))
      )
```

### Articles per Day

```{r}
valueBox(tot_obs, caption = "Number of observations linked to craywatch",
         icon = "ion-android-cloud-done")
```

Row
-------------------------------------

### Number of observations per dataset

```{r}
cray_df %>%
  count(datasetName) %>%
  mutate(datasetName = reorder(datasetName, n)) %>%
  ggplot(aes(x = datasetName, y = n)) +
    geom_bar(stat = "identity",
             fill = "cornflowerblue") +
    geom_text(aes(label = n), vjust = 0, hjust = 0) +
    scale_x_discrete(label = function(x) stringr::str_trunc(x, 30)) +
    scale_y_continuous(limits = c(0, 1300)) +
    labs(x = "", y = "Number of observations") +
    theme_minimal() +
    coord_flip()
```
